language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t brucebotes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brucebotes/react-test npm run test

after_success:
  - docker build -t brucebotes/multi-client ./client
  - docker build -t brucebotes/multi-nginx ./nginx
  - docker build -t brucebotes/multi-server ./server
  - docker build -t brucebotes/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push brucebotes/multi-client
  - docker push brucebotes/multi-nginx
  - docker push brucebotes/multi-server
  - docker push brucebotes/multi-worker


    #deploy: 
    #  provider: elasticbeanstalk
    #  region: "ap-south-1"
    #  app: "docker-react"
    #  env: "Dockerreact-env"
    #  bucket_name: "elasticbeanstalk-ap-south-1-375665553387"
    #  bucket_path: "docker-react"
    #  on:
    #    branch: master
    #  access_key_id: $AWS_ACCESS_KEY
    #  secret_access_key: $AWS_SECRET_KEY



